"""Scene プロトコル。各画面はこれを満たす。"""
from __future__ import annotations

from typing import Protocol, Any

import pygame


class Scene(Protocol):
    def on_enter(self, ctx: Any) -> None: ...
    def on_exit(self) -> None: ...
    def handle_event(self, event: Any) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self, surface: pygame.Surface) -> None: ...
